services:
  postgres:
    image: postgres:16.10-alpine3.22
    environment:
      - 'POSTGRES_DB=meditracker'
      - 'POSTGRES_PASSWORD=meditracker_pass'
      - 'POSTGRES_USER=myuser'
    ports:
          - '5432'